server:
  port: 8888
  servlet:
    context-path: /newWorld

#actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'

#rabbitmq, why need force add listener:simple:acknowledge-mode: manual ????
#          java configure doesn't work
spring:
  rabbitmq:
    user: guest
    password: guest
    port: 5672
    host: localhost
    publisher-returns: true
    publisher-confirm-type: correlated
  redis:
    database: 0
    host: localhost
    port: 6379

  profiles:
    active: id-dev
